-- DDL APP DE SERVICIOS

DROP DATABASE IF EXISTS proyecto_appservcios;

CREATE DATABASE proyecto_appservcios;

USE proyecto_appservcios;

-- Tabla SOLICITUD
CREATE TABLE SOLICITUD (
    ID_SOLICITUD INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT,
    ID_TIPODESERVICIO INT,
    ID_EMPLEADOS INT,
    FECHA DATETIME,
    ID_MEDIO_DE_PAGO INT
);

-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    ID_PARTICULARES INT,
    ID_EMPRESAS INT
);

-- Tabla PARTICULARES
CREATE TABLE PARTICULARES (
    ID_PARTICULARES INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'USUARIO_UNKNOW',
    TELEFONO VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL, 
    DOCUMENTO VARCHAR(10) UNIQUE NOT NULL
);

-- Tabla EMPRESAS
CREATE TABLE EMPRESAS (
    ID_EMPRESAS INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'USUARIO_UNKNOW',
    TELEFONO VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL 
);

-- Tabla EMPLEADOS
CREATE TABLE EMPLEADO (
    ID_EMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100),
    ID_TIPODESERVICIO INT,
    DISPONIBILIDAD BOOLEAN,
    CALIFICACION INT
);

-- Tabla TIPODESERVICIO
CREATE TABLE TIPODESERVICIO (
    ID_TIPODESERVICIO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(50)
);

-- Tabla MEDIODEPAGO
CREATE TABLE MEDIODEPAGO (
    ID_MEDIO_DE_PAGO INT PRIMARY KEY AUTO_INCREMENT,
    EFECTIVO INT,
    TARJETA INT,
    BILLETERA_VIRTUAL INT,
    ACREDITADO BOOLEAN
);

-- FOREIGN KEYS

-- EMPLEADO

ALTER TABLE EMPLEADO
    ADD CONSTRAINT FK_EMP_TIPODESERVICIO
    FOREIGN KEY (ID_TIPODESERVICIO) REFERENCES TIPODESERVICIO(ID_TIPODESERVICIO);
    
-- CLIENTE

ALTER TABLE CLIENTE
    ADD CONSTRAINT FK_CLIENTE_PARTICULARES
    FOREIGN KEY (ID_PARTICULARES) REFERENCES PARTICULARES(ID_PARTICULARES);

ALTER TABLE CLIENTE
    ADD CONSTRAINT FK_CLIENTE_EMPRESAS
    FOREIGN KEY (ID_EMPRESAS) REFERENCES EMPRESAS(ID_EMPRESAS);

-- SOLICITUD

ALTER TABLE SOLICITUD
    ADD CONSTRAINT FK_SOLICITUD_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE SOLICITUD
    ADD CONSTRAINT FK_SOLICITUD_EMPLEADO
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO);

ALTER TABLE SOLICITUD
    ADD CONSTRAINT FK_SOLICITUD_TIPODESERVICIO
    FOREIGN KEY (ID_TIPODESERVICIO) REFERENCES TIPODESERVICIO(ID_TIPODESERVICIO);
    
ALTER TABLE SOLICITUD
    ADD CONSTRAINT FK_SOLICITUD_MEDIODEPAGO
    FOREIGN KEY (ID_MEDIODEPAGO) REFERENCES MEDIODEPAGO(ID_MEDIODEPAGO);

-- Tabla de Notificaciones
--Para enviar notificaciones a clientes y empleados sobre servicios, promociones, etc.
CREATE TABLE NOTIFICACIONES (
    ID_NOTIFICACION INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT,
    ID_EMPLEADO INT,
    MENSAJE TEXT,
    FECHA DATETIME,
    LEIDO BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

--Tabla de Facturas
--Para gestionar la facturación de los servicios prestados a los clientes.
CREATE TABLE FACTURAS (
    ID_FACTURA INT PRIMARY KEY AUTO_INCREMENT,
    ID_SOLICITUD INT,
    FECHA_FACTURA DATETIME,
    TOTAL DECIMAL(10, 2),
    PAGADO BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD(ID_SOLICITUD)
);

--Tabla de Tiempos de Servicio
--Para registrar los tiempos estimados y reales de realización de los servicios.
CREATE TABLE TIEMPOS_SERVICIO (
    ID_TIEMPO INT PRIMARY KEY AUTO_INCREMENT,
    ID_SOLICITUD INT,
    TIEMPO_ESTIMADO INT, -- en minutos
    TIEMPO_REAL INT,     -- en minutos
    FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD(ID_SOLICITUD)
);

--Tabla de Comentarios/Reseñas
--Para permitir a los clientes dejar comentarios y calificaciones sobre los servicios prestados.
CREATE TABLE COMENTARIOS (
    ID_COMENTARIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_SOLICITUD INT,
    ID_CLIENTE INT,
    CALIFICACION INT CHECK (CALIFICACION BETWEEN 1 AND 5),
    COMENTARIO TEXT,
    FECHA DATETIME,
    FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD(ID_SOLICITUD),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);


-- Relaciones de las Nuevas Tablas
-- Tabla de Comentarios/Reseñas
ALTER TABLE COMENTARIOS
ADD CONSTRAINT FK_COMENTARIOS_SOLICITUD
FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD(ID_SOLICITUD);

ALTER TABLE COMENTARIOS
ADD CONSTRAINT FK_COMENTARIOS_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);

--Tabla de Notificaciones
ALTER TABLE NOTIFICACIONES
ADD CONSTRAINT FK_NOTIFICACIONES_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE NOTIFICACIONES
ADD CONSTRAINT FK_NOTIFICACIONES_EMPLEADO
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO);


--Tabla de Tiempos de Servicio
ALTER TABLE TIEMPOS_SERVICIO
ADD CONSTRAINT FK_TIEMPOS_SERVICIO_SOLICITUD
FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD(ID_SOLICITUD);

--Tabla de Facturas
ALTER TABLE FACTURAS
ADD CONSTRAINT FK_FACTURAS_SOLICITUD
FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD(ID_SOLICITUD);

