
-- Vista de Cantidad de Medios de Pago Utilizados en las Solicitudes
CREATE VIEW VISTA_CANTIDAD_MEDIOS_PAGO AS
SELECT 
    m.ID_MEDIO_DE_PAGO,
    CASE
        WHEN m.EFECTIVO IS NOT NULL THEN 'Efectivo'
        WHEN m.TARJETA IS NOT NULL THEN 'Tarjeta'
        WHEN m.BILLETERA_VIRTUAL IS NOT NULL THEN 'Billetera Virtual'
    END AS TIPO_MEDIO_PAGO,
    COUNT(s.ID_SOLICITUD) AS CANTIDAD_USOS
FROM 
    MEDIODEPAGO m
LEFT JOIN 
    SOLICITUD s ON m.ID_MEDIO_DE_PAGO = s.ID_MEDIO_DE_PAGO
GROUP BY 
    m.ID_MEDIO_DE_PAGO, TIPO_MEDIO_PAGO;

--Cómo Utilizar la Vista
SELECT * FROM VISTA_CANTIDAD_MEDIOS_PAGO;

