-- DDL APP DE SERVICIOS

DROP DATABASE IF EXISTS proyecto_appservcios;

CREATE DATABASE proyecto_appservcios;

USE proyecto_appservcios;

-- Tabla SOLICITUD
CREATE TABLE SOLICITUD (
    ID_SOLICITUD INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT,
    ID_TIPODESERVICIO INT,
    ID_EMPLEADOS INT,
    FECHA DATETIME,
    ID_MEDIO_DE_PAGO INT,
);

-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    ID_PARTICULARES INT,
    ID_EMPRESAS INT
);

-- Tabla PARTICULARES
CREATE TABLE PARTICULARES (
    ID_PARTICULARES INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'USUARIO_UNKNOW',
    TELEFONO VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL 
);

-- Tabla EMPRESAS
CREATE TABLE EMPRESAS (
    ID_EMPRESAS INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'USUARIO_UNKNOW',
    TELEFONO VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL 
);

-- Tabla EMPLEADOS
CREATE TABLE EMPLEADO (
    ID_EMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100),
    ESPECIALIDAD INT,
    DISPONIBILIDAD BOOLEAN,
    CALIFICACION INT
);

-- Tabla TIPODESERVICIO
CREATE TABLE TIPODESERVICIO (
    ID_TIPODESERVICIO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(50)
);

-- Tabla MEDIODEPAGO
CREATE TABLE MEDIODEPAGO (
    ID_MEDIO_DE_PAGO INT PRIMARY KEY AUTO_INCREMENT,
    EFECTIVO INT,
    TARJETA INT,
    BILLETERA_VIRTUAL INT
);

-- FOREIGN KEYS

-- EMPLEADO

ALTER TABLE EMPLEADOS
    ADD CONSTRAINT FK_EMP_TIPODESERVICIO
    FOREIGN KEY (ID_TIPODESERVICIO) REFERENCES TIPODESERVICIO(ID_TIPODESERVICIO);
    
-- CLIENTE

ALTER TABLE CLIENTE
    ADD CONSTRAINT FK_CLIENTE_PARTICULARES
    FOREIGN KEY (ID_PARTICULARES) REFERENCES PARTICULARES(ID_PARTICULARES);

ALTER TABLE CLIENTE
    ADD CONSTRAINT FK_CLIENTE_EMPRESAS
    FOREIGN KEY (ID_EMPRESAS) REFERENCES EMPRESAS(ID_EMPRESAS);
    
-- SOLICITUD

ALTER TABLE SOLICITUD
    ADD CONSTRAINT FK_SOLICITUD_CLIENTE
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE SOLICITUD
    ADD CONSTRAINT FK_SOLICITUD_EMPLEADO
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO);

ALTER TABLE SOLICITUD
    ADD CONSTRAINT FK_SOLICITUD_TIPODESERVICIO
    FOREIGN KEY (ID_TIPODESERVICIO) REFERENCES TIPODESERVICIO(ID_TIPODESERVICIO);
    
ALTER TABLE SOLICITUD
    ADD CONSTRAINT FK_SOLICITUD_MEDIODEPAGO
    FOREIGN KEY (ID_MEDIODEPAGO) REFERENCES MEDIODEPAGO(ID_MEDIODEPAGO);
