-- Vista de Evaluaciones de Empleados
CREATE VIEW VISTA_EVALUACIONES_EMPLEADOS AS
SELECT e.ID_EMPLEADO, e.NOMBRE, e.TELEFONO, e.EMAIL, e.CALIFICACION, 
       COUNT(s.ID_SOLICITUD) AS NUM_SOLICITUDES_ATENDIDAS
FROM EMPLEADO e
LEFT JOIN SOLICITUD s ON e.ID_EMPLEADO = s.ID_EMPLEADOS
GROUP BY e.ID_EMPLEADO, e.NOMBRE, e.TELEFONO, e.EMAIL, e.CALIFICACION;


-- Vista de Medios de Pago Utilizados
CREATE VIEW VISTA_MEDIOS_DE_PAGO AS
SELECT m.ID_MEDIO_DE_PAGO, 
       COUNT(f.ID_FACTURA) AS NUM_FACTURAS,
       SUM(f.TOTAL) AS TOTAL_VENDIDO
FROM MEDIODEPAGO m
LEFT JOIN FACTURAS f ON m.ID_MEDIO_DE_PAGO = f.METODO_PAGO
GROUP BY m.ID_MEDIO_DE_PAGO;
